version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 992382799947.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t test53private .
      - docker tag test53private:latest 992382799947.dkr.ecr.us-east-1.amazonaws.com/test53private:latest
  post_build:
    commands:
      - docker push 992382799947.dkr.ecr.us-east-1.amazonaws.com/test53private:latest
      - echo Writing image definitions file...
      - printf '[{"name":"ml web","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json